const handler = (api) => {
	api.addBase({"body":{"fontFeatureSettings":"'rlig' 1, 'calt' 1"},"html":{"@apply scroll-smooth bg-antique leading-5 text-gray mix-blend-normal selection:bg-red selection:text-white":true,"textRendering":"optimizeLegibility","fontSynthesis":"none"},"a":{"WebkitTapHighlightColor":"transparent"},"h1":{"@apply h1":true},"h2":{"@apply h2":true},"h3":{"@apply h3":true},"h4":{"@apply h4":true},"h5":{"@apply h5":true},"p":{"@apply p":true},"blockquote":{"@apply blockquote":true},"ul":{"@apply my-6 ml-6 list-disc [&>li]:mt-2":true},"code":{"@apply relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold":true},":root":{"--font-sans":"Lausanne, Lausanne Fallback","--antique":"32 100% 98%","--white":"0 0% 100%","--gray":"0 0% 9%","--light-gray":"0 0% 16.86%","--highlight-gray":"0 0% 20.78%","--red":"2 100% 59%","--blue":"187 43% 73%","--yellow":"54 100% 68%","--orange":"36 97% 64%","--background":"0 0% 100%","--foreground":"0 0% 3.9%","--card":"0 0% 100%","--card-foreground":"0 0% 3.9%","--popover":"0 0% 100%","--popover-foreground":"0 0% 3.9%","--primary":"0 0% 9%","--primary-foreground":"0 0% 98%","--secondary":"0 0% 96.1%","--secondary-foreground":"0 0% 9%","--muted":"0 0% 96.1%","--muted-foreground":"0 0% 45.1%","--accent":"0 0% 96.1%","--accent-foreground":"0 0% 9%","--destructive":"0 84.2% 60.2%","--destructive-foreground":"0 0% 98%","--border":"0 0% 89.8%","--input":"0 0% 89.8%","--ring":"0 0% 3.9%","--radius":"0.5rem"},".dark":{"--background":"0 0% 3.9%","--foreground":"0 0% 98%","--card":"0 0% 3.9%","--card-foreground":"0 0% 98%","--popover":"0 0% 3.9%","--popover-foreground":"0 0% 98%","--primary":"0 0% 98%","--primary-foreground":"0 0% 9%","--secondary":"0 0% 14.9%","--secondary-foreground":"0 0% 98%","--muted":"0 0% 14.9%","--muted-foreground":"0 0% 63.9%","--accent":"0 0% 14.9%","--accent-foreground":"0 0% 98%","--destructive":"0 62.8% 30.6%","--destructive-foreground":"0 0% 98%","--border":"0 0% 14.9%","--input":"0 0% 14.9%","--ring":"0 0% 83.1%"}});
		api.addComponents({".h1":{"@apply scroll-m-20 text-4xl font-extrabold tracking-tight":true,"@apply mb-9 md:text-7xl xl:text-8xl":true},".h2":{"@apply scroll-m-20 text-3xl font-semibold tracking-tight transition-colors first:mt-0":true,"@apply my-9 md:text-6xl xl:text-7xl":true},".h3":{"@apply scroll-m-20 text-2xl font-semibold tracking-tight":true,"@apply mb-7 mt-9 md:text-5xl xl:text-6xl":true},".h4":{"@apply scroll-m-20 text-xl font-semibold tracking-tight":true,"@apply mb-4 mt-6 md:text-4xl":true},".h5":{"@apply text-lg md:text-3xl":true,"@apply mb-2 mt-4":true},".large":{"@apply text-lg font-semibold md:text-3xl":true,"@apply my-2":true},".p":{"@apply leading-7 [&:not(:first-child)]:mt-6":true,"@apply md:text-lg":true},".label":{"@apply text-base uppercase":true},".blockquote":{"@apply mt-6 border-l-2 pl-6 italic":true},".lead":{"@apply text-xl text-muted-foreground":true},".small":{"@apply text-sm font-medium leading-none":true},".muted":{"@apply text-sm text-muted-foreground":true},".disabled":{"@apply cursor-not-allowed border-neutral-200 bg-neutral-50 text-neutral-500 opacity-60":true},".pointer-events-all":{"pointerEvents":"all"},".pt-header":{"@apply pt-[6.5rem] md:pt-[8.5rem]":true},".rotating-text":{"@apply absolute bottom-0 left-0 right-0 top-0 h-full w-full animate-spin text-antique transition-opacity duration-300 ease-linear":true,"animationDuration":"20s"},".arrow-animate":{"transform":"rotate(-45deg) translate3d(25%, 0, 0)"},".red-underline":{"backgroundImage":"linear-gradient(\n\t\t\t90deg,\n\t\t\ttransparent 0%,\n\t\t\ttransparent 33.33%,\n\t\t\tcurrentColor 33.33%,\n\t\t\tcurrentColor 66.66%,\n\t\t\ttransparent 66%,\n\t\t\ttransparent 100%\n\t\t)","backgroundSize":"300px 6px","&-in":{"transition":"background-position 600ms 600ms cubic-bezier(0.4, 0, 0.2, 1),\n\t\t\t\tcolor 600ms cubic-bezier(0.4, 0, 0.2, 1)"},"&-out":{"transition":"background-position 600ms cubic-bezier(0.4, 0, 0.2, 1),\n\t\t\t\tcolor 300ms 100ms cubic-bezier(0.4, 0, 0.2, 1)","color":"unset"}},".rich-text *":{"whiteSpace":"pre-wrap"},".rich-text":{"> *:first-child":{"marginTop":"0"},"hr":{"borderRadius":"0","height":"3px","margin":"6rem 0","width":"3rem","border":"0","background":"var(--gray)"},"a":{"color":"inherit","textDecoration":"none","position":"relative","display":"inline-flex","padding":"0 2px","overflow":"hidden","&:before":{"content":"''","position":"absolute","zIndex":-1,"top":"0","left":"0","transform":"translateY(calc(100% - 2px))","width":"100%","height":"100%","backgroundColor":"var(--red)","opacity":0.85,"transition":"transform 0.25s ease-out"},"&:hover":{"color":"var(--antique)","&::before":{"transform":"translateY(0)","transition":"transform 0.25s ease-out"}}}},".fullscreen-media":{"height":"calc(100% + 220px)"},".content-collage-rich-text":{"h2":{"@apply h1":true},"p":{"@apply mx-auto my-0 max-w-[16rem]":true}}});
};

const config = {};

module.exports = {
	handler,
	config,
};