services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    image: redis:7.0.4-alpine3.16
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis_password
    volumes:
      - cache:/data
    deploy:
      resources:
        limits:
          cpus: '${DOCKER_REDIS_CPUS-0}'
          memory: '${DOCKER_REDIS_MEMORY-0}'

volumes:
  mongo_data:
  cache:
