/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
	collections: {
		pages: Page
		studies: Study
		media: Media
		'form-submissions': FormSubmission
		categories: Category
		users: User
	}
	globals: {
		'mega-menu': MegaMenu
		'social-media': SocialMedia
		footer: Footer
	}
}
export interface Page {
	id: string
	title: string
	heroType: 'minimal' | 'contentAboveImage' | 'contentLeftOfImage'
	layout?: (
		| {
				ctaFields: {
					feature: 'none' | 'cpa'
					links?: {
						link: {
							type?: 'reference' | 'custom'
							newTab?: boolean
							reference: {
								value: string | Page
								relationTo: 'pages'
							}
							url: string
							label: string
						}
						id?: string
					}[]
				}
				id?: string
				blockName?: string
				blockType: 'cta'
		  }
		| {
				backgroundColor?: 'none' | 'red' | 'blue' | 'orange'
				columns?: {
					width: 'oneThird' | 'half' | 'twoThirds' | 'full'
					alignment: 'left' | 'center' | 'right'
					content: {
						[k: string]: unknown
					}[]
					id?: string
				}[]
				accentLine?: boolean
				accentLineAlignment?: 'left' | 'right'
				paddingTop?: 'none' | 'small' | 'medium' | 'large'
				paddingBottom?: 'none' | 'small' | 'medium' | 'large'
				id?: string
				blockName?: string
				blockType: 'content'
		  }
		| {
				size: 'small' | 'medium' | 'large'
				id?: string
				blockName?: string
				blockType: 'spacer'
		  }
	)[]
	slug?: string
	meta?: {
		title?: string
		description?: string
		keywords?: string
	}
	updatedAt: string
	createdAt: string
}
export interface Study {
	id: string
	title: string
	featuredImage: string | Media
	client?: string
	location?: string
	categories?: string[] | Category[]
	slug?: string
	meta?: {
		title?: string
		description?: string
		keywords?: string
	}
	updatedAt: string
	createdAt: string
}
export interface Media {
	id: string
	alt: string
	updatedAt: string
	createdAt: string
	url?: string
	filename?: string
	mimeType?: string
	filesize?: number
	width?: number
	height?: number
	sizes?: {
		card?: {
			url?: string
			width?: number
			height?: number
			mimeType?: string
			filesize?: number
			filename?: string
		}
		feature?: {
			url?: string
			width?: number
			height?: number
			mimeType?: string
			filesize?: number
			filename?: string
		}
	}
}
export interface Category {
	id: string
	title: string
	slug?: string
	updatedAt: string
	createdAt: string
}
export interface FormSubmission {
	id: string
	from?: string
	message?: string
	source?: string
	updatedAt: string
	createdAt: string
}
export interface User {
	id: string
	updatedAt: string
	createdAt: string
	email: string
	resetPasswordToken?: string
	resetPasswordExpiration?: string
	salt?: string
	hash?: string
	loginAttempts?: number
	lockUntil?: string
	password?: string
}
export interface MegaMenu {
	id: string
	nav?: {
		link: {
			type?: 'reference' | 'custom'
			newTab?: boolean
			reference: {
				value: string | Page
				relationTo: 'pages'
			}
			url: string
			label: string
			appearance?: 'default' | 'primary' | 'secondary'
		}
		id?: string
	}[]
	updatedAt?: string
	createdAt?: string
}
export interface SocialMedia {
	id: string
	links?: {
		label: string
		url: string
		id?: string
	}[]
	updatedAt?: string
	createdAt?: string
}
export interface Footer {
	id: string
	nav?: {
		link: {
			type?: 'reference' | 'custom'
			newTab?: boolean
			reference: {
				value: string | Page
				relationTo: 'pages'
			}
			url: string
			label: string
			appearance?: 'default' | 'primary' | 'secondary'
		}
		id?: string
	}[]
	updatedAt?: string
	createdAt?: string
}
